"""Impose plan schema — sheet-level step-and-repeat layout document.

The plan is a thin envelope around the parameters Compile forwards to
:func:`codex_pdf.geom.tile_grid`; **no Compile-side layout math** —
every cell position comes from Codex (spec §4.1, enforced by the
consume-surface audit script).

Two ingestion-time choices live in this schema (not in codex):

* ``page_mapping`` — ``sequential`` (input page N → cell N) or
  ``repeat`` (every cell carries input page 0). ``sequential``
  multi-sheet output is generated by paginating across sheets when
  ``input_pages > cells_per_sheet``; ``repeat`` always emits one
  sheet (front) plus one back sheet if back-side is enabled.
* ``back_side`` — ``none`` (front only), ``work-and-turn`` (back is
  the front mirrored about the vertical sheet center), or
  ``work-and-tumble`` (back is the front mirrored about the
  horizontal sheet center). Codex doesn't model back-side directly;
  Compile derives the back placements from the front placements via
  a deterministic transform.

``bleed_handling`` values match codex 1.7.0 GEOM_SCHEMA_VERSION 1.1.0
exactly (``none`` / ``trim`` / ``extend``). The aspirational
``overlap`` / ``mirror`` values from earlier docs are unsupported in
this v1 schema; document changes will land alongside the upstream
codex extension if they ship.
"""

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, Field, NonNegativeFloat, PositiveFloat, RootModel

# --- Sub-shapes ---------------------------------------------------------


class _Strict(BaseModel):
    model_config = {"extra": "forbid", "frozen": True}


class Sheet(_Strict):
    """Output sheet dimensions in points."""

    width_pt: PositiveFloat
    height_pt: PositiveFloat


class Cell(_Strict):
    """Per-cell dimensions in points (matches the input page TrimBox)."""

    width_pt: PositiveFloat
    height_pt: PositiveFloat


class Gutter(_Strict):
    """Inter-cell spacing in points. Asymmetric x/y is supported."""

    x_pt: NonNegativeFloat = 0.0
    y_pt: NonNegativeFloat = 0.0


class MarksZoneSpec(_Strict):
    """Reserved sheet margins consumed by the marks layer (slug, color
    bars, etc.). Forwarded into ``codex_pdf.geom.MarksZone`` at engine
    time. The ``Spec`` suffix avoids shadowing the Codex type — the
    consume-surface audit flags any Compile-side class that re-declares
    a Codex type name."""

    top_pt: NonNegativeFloat = 0.0
    right_pt: NonNegativeFloat = 0.0
    bottom_pt: NonNegativeFloat = 0.0
    left_pt: NonNegativeFloat = 0.0


# --- Top-level plan ------------------------------------------------------


PageMapping = Literal["sequential", "repeat"]
BackSideMode = Literal["none", "work-and-turn", "work-and-tumble"]
BleedHandling = Literal["none", "trim", "extend"]
CellRotation = Literal[0, 90, 180, 270]


class ImposePlan(BaseModel):
    """Sheet-level step-and-repeat plan — schema-versioned, fully forward-
    compatible with codex's GEOM_SCHEMA_VERSION 1.1.0 surface."""

    model_config = {"extra": "forbid"}

    schema_version: Literal["1.0.0"] = Field(
        default="1.0.0",
        description="Bumps when the plan-document schema changes (per producer; spec §6.2).",
    )
    sheet: Sheet
    cell: Cell
    gutter: Gutter = Field(default_factory=Gutter)
    marks_zone: MarksZoneSpec = Field(default_factory=MarksZoneSpec)
    cell_rotation: CellRotation = 0
    flip_per_row: bool = False
    bleed_pt: NonNegativeFloat = 0.0
    bleed_handling: BleedHandling = "none"
    page_mapping: PageMapping = "sequential"
    back_side: BackSideMode = "none"


class ImposePlanRoot(RootModel[ImposePlan]):
    """Root model — emit JSON Schema directly without a wrapping object."""


def impose_plan_json_schema() -> dict[str, object]:
    """Return the JSON Schema for an impose plan document.

    Surfaced via ``compile-pdf impose-schema`` and (once api/main mounts
    the schema endpoint) ``GET /v1/schema/impose``.
    """
    return ImposePlan.model_json_schema()


__all__ = [
    "BackSideMode",
    "BleedHandling",
    "Cell",
    "CellRotation",
    "Gutter",
    "ImposePlan",
    "ImposePlanRoot",
    "MarksZoneSpec",
    "PageMapping",
    "Sheet",
    "impose_plan_json_schema",
]
