"""Impose plan schema — sheet-level step-and-repeat layout document.

The plan is a thin envelope around the parameters Compile forwards to
:func:`codex_pdf.geom.tile_grid`; **no Compile-side layout math** —
every cell position comes from Codex (spec §4.1, enforced by the
consume-surface audit script).

Two ingestion-time choices live in this schema (not in codex):

* ``page_mapping`` — ``sequential`` (input page N → cell N) or
  ``repeat`` (every cell carries input page 0). ``sequential``
  multi-sheet output is generated by paginating across sheets when
  ``input_pages > cells_per_sheet``; ``repeat`` always emits one
  sheet (front) plus one back sheet if back-side is enabled.
* ``back_side`` — ``none`` (front only), ``work-and-turn`` (back is
  the front mirrored about the vertical sheet center), or
  ``work-and-tumble`` (back is the front mirrored about the
  horizontal sheet center). Codex doesn't model back-side directly;
  Compile derives the back placements from the front placements via
  a deterministic transform.

``bleed_handling`` values match codex 1.7.0 GEOM_SCHEMA_VERSION 1.1.0
exactly (``none`` / ``trim`` / ``extend``). The aspirational
``overlap`` / ``mirror`` values from earlier docs are unsupported in
this v1 schema; document changes will land alongside the upstream
codex extension if they ship.

Explicit placements (additive, schema 1.1.0):

* ``explicit_placements`` — when set, the engine bypasses
  ``codex_pdf.geom.tile_grid`` and drops each cell at the
  solver-provided sheet-space box. This is the handoff seam for
  sift-pdf's stagger / gang / nest tiers, whose layouts are *not*
  uniform grids and so cannot be expressed via the grid knobs.
  sift-pdf computes the positions (it owns the solver); Compile only
  writes them. This keeps the consume-surface boundary intact — Compile
  still does no *grid* layout math; it places pre-solved boxes.
* ``stagger_mode`` — first-class record of the solver's stagger intent
  (half-drop / brick / custom) so it survives through the writer layer
  into lineage, rather than being lost once positions are flattened
  into ``explicit_placements`` coordinates. Informational for the
  engine (placements already carry the resolved coordinates); recorded
  for downstream consumers and audit.
"""

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, Field, NonNegativeFloat, PositiveFloat, RootModel

# --- Sub-shapes ---------------------------------------------------------


class _Strict(BaseModel):
    model_config = {"extra": "forbid", "frozen": True}


class Sheet(_Strict):
    """Output sheet dimensions in points."""

    width_pt: PositiveFloat
    height_pt: PositiveFloat


class Cell(_Strict):
    """Per-cell dimensions in points (matches the input page TrimBox)."""

    width_pt: PositiveFloat
    height_pt: PositiveFloat


class Gutter(_Strict):
    """Inter-cell spacing in points. Asymmetric x/y is supported."""

    x_pt: NonNegativeFloat = 0.0
    y_pt: NonNegativeFloat = 0.0


class MarksZoneSpec(_Strict):
    """Reserved sheet margins consumed by the marks layer (slug, color
    bars, etc.). Forwarded into ``codex_pdf.geom.MarksZone`` at engine
    time. The ``Spec`` suffix avoids shadowing the Codex type — the
    consume-surface audit flags any Compile-side class that re-declares
    a Codex type name."""

    top_pt: NonNegativeFloat = 0.0
    right_pt: NonNegativeFloat = 0.0
    bottom_pt: NonNegativeFloat = 0.0
    left_pt: NonNegativeFloat = 0.0


# --- Top-level plan ------------------------------------------------------


PageMapping = Literal["sequential", "repeat"]
BackSideMode = Literal["none", "work-and-turn", "work-and-tumble"]
BleedHandling = Literal["none", "trim", "extend"]
CellRotation = Literal[0, 90, 180, 270]
StaggerMode = Literal["none", "half-drop-x", "half-drop-y", "custom"]


class ExplicitPlacement(BaseModel):
    """One pre-solved cell position in sheet space.

    Emitted by sift-pdf's solver (stagger / gang / nest tiers) and
    consumed by the impose engine when a uniform grid can't express the
    layout. The box (``x0_pt``/``y0_pt``/``x1_pt``/``y1_pt``) plus
    ``rotation`` + ``flip_h`` / ``flip_v`` mirror codex's ``CellPlacement``
    vocabulary so the engine's per-cell transform path is identical to
    the grid path. Field names + types match sift-pdf's handoff dict
    (``sift_pdf.handoff.compile._explicit_plan``) exactly so the dict
    validates without translation.
    """

    model_config = {"extra": "forbid"}

    source_ref: str = Field(
        ...,
        description=(
            "Solver back-reference — sift's Job.id, optionally with a "
            "':pageIdx' suffix. Informational for the engine; carried into "
            "lineage so a placed cell can be traced to its source job."
        ),
    )
    x0_pt: float = Field(..., description="Lower-left x of the cell box in sheet-space points.")
    y0_pt: float = Field(..., description="Lower-left y of the cell box in sheet-space points.")
    x1_pt: float = Field(..., description="Upper-right x of the cell box in sheet-space points.")
    y1_pt: float = Field(..., description="Upper-right y of the cell box in sheet-space points.")
    rotation: float = Field(
        default=0.0,
        description="Cell rotation in degrees, counter-clockwise (PDF convention).",
    )
    flip_h: bool = Field(
        default=False, description="Mirror the cell content about its vertical axis."
    )
    flip_v: bool = Field(
        default=False, description="Mirror the cell content about its horizontal axis."
    )
    row: int | None = Field(
        default=None,
        description="Grid row index, informational. Optional — sift omits it for nest layouts.",
    )
    col: int | None = Field(
        default=None,
        description="Grid column index, informational. Optional — sift omits it for nest layouts.",
    )


class ImposePlan(BaseModel):
    """Sheet-level step-and-repeat plan — schema-versioned, fully forward-
    compatible with codex's GEOM_SCHEMA_VERSION 1.1.0 surface."""

    model_config = {"extra": "forbid"}

    schema_version: Literal["1.0.0"] = Field(
        default="1.0.0",
        description="Bumps when the plan-document schema changes (per producer; spec §6.2).",
    )
    sheet: Sheet
    cell: Cell
    gutter: Gutter = Field(default_factory=Gutter)
    marks_zone: MarksZoneSpec = Field(default_factory=MarksZoneSpec)
    cell_rotation: CellRotation = 0
    flip_per_row: bool = False
    bleed_pt: NonNegativeFloat = 0.0
    bleed_handling: BleedHandling = "none"
    page_mapping: PageMapping = "sequential"
    back_side: BackSideMode = "none"
    registration_marks: bool = Field(
        default=False,
        description=(
            "When true, place four-color registration targets in the reserved "
            "``marks_zone`` corners. Wave 1 plumb-only — the engine accepts "
            "the field but mark rendering ships in a follow-up once the "
            "upstream codex marks API stabilizes; until then the toggle "
            "round-trips through the policy without producing visible output."
        ),
    )
    crop_marks: bool = Field(
        default=False,
        description=(
            "When true, place crop marks at the per-cell trim corners. "
            "Same plumb-only semantics as ``registration_marks``: the schema "
            "carries the operator's intent end-to-end for editor UIs and "
            "lineage records, with engine rendering deferred to a follow-up."
        ),
    )
    explicit_placements: list[ExplicitPlacement] | None = Field(
        default=None,
        description=(
            "Pre-solved sheet-space cell positions from an upstream solver "
            "(sift-pdf stagger / gang / nest). When present, the engine places "
            "cells at these exact boxes instead of computing a uniform grid via "
            "``codex_pdf.geom.tile_grid``; the grid knobs (``gutter``, "
            "``cell_rotation``, ``flip_per_row``) are ignored. ``None`` (the "
            "default) preserves the prior grid behaviour exactly — this field "
            "is purely additive."
        ),
    )
    stagger_mode: StaggerMode = Field(
        default="none",
        description=(
            "Records the solver's stagger intent (half-drop / brick / custom) "
            "so it survives into lineage. Informational for the engine: when "
            "``explicit_placements`` is set the resolved coordinates already "
            "carry the offset; this field preserves the *semantic* intent that "
            "would otherwise be lost once positions are flattened. Defaults to "
            "``none`` (uniform grid)."
        ),
    )


class ImposePlanRoot(RootModel[ImposePlan]):
    """Root model — emit JSON Schema directly without a wrapping object."""


def impose_plan_json_schema() -> dict[str, object]:
    """Return the JSON Schema for an impose plan document.

    Surfaced via ``compile-pdf impose-schema`` and (once api/main mounts
    the schema endpoint) ``GET /v1/schema/impose``.
    """
    return ImposePlan.model_json_schema()


__all__ = [
    "BackSideMode",
    "BleedHandling",
    "Cell",
    "CellRotation",
    "ExplicitPlacement",
    "Gutter",
    "ImposePlan",
    "ImposePlanRoot",
    "MarksZoneSpec",
    "PageMapping",
    "Sheet",
    "StaggerMode",
    "impose_plan_json_schema",
]
